### ISSUE TITLE
Add support for High Sierra

### ISSUE THREAD

**Issue by whatnameisit** [0xFireWolf/GenericCardReaderFriend#1]
I've tested the kext on High Sierra and it works OK for Realtek 0bda0138.
![Screen Shot 2021-07-30 at 9 36 13 AM](https://user-images.githubusercontent.com/47713349/127582984-6d77fcb6-85f8-49c3-9519-4807ff858640.png)

[Lilu_1.5.4_17.7.txt](https://github.com/0xFireWolf/GenericCardReaderFriend/files/6904403/Lilu_1.5.4_17.7.txt)
Thanks!

**Comment by 0xFireWolf** [comment]
Thank you for testing. Resolved by [v1.0.1](https://github.com/0xFireWolf/GenericCardReaderFriend/releases/tag/1.0.1)
